export const LOGIN = 'Login'
export const REGISTER = 'Register'
export const TEXT_ERROR = 'Error'  //Email ou mot de passe incorrect.
export const HOME_URL = 'http://localhost:3000/home'
export const REGISTER_URL = 'http://localhost:3000/auth/register'
export const LOGIN_URL = 'http://localhost:3000/auth/login'
export const PROFILE_URL = 'http://localhost:3000/profile'
export const LOGIN_INTO_ACCOUNT = 'Log in into you account';
export const CREATE_YOUR_ACCOUNT = 'Create you account';
export const FORGOT_PASSWORD = 'Forgot password ?';
export const RESET_YOUR_PASSWORD = 'Reset your password';
export const CONNECT_WITH_GOOGLE = 'Connect with Google';
export const DEMARRER_BARATHON = 'Démarrer un barathon';
export const DEMARRER_PARTIE = 'Démarrer la partie';
export const NOMBRE_BAR_VISITER = 'Nombre de bars à visiter';
export const RAYON_BARATHON = 'Rayon du Barathon (en km)';
export const TEMPS_TOTAL = 'Temps total';
export const ARRETER = 'Arrêter';
export const BARS_RESTANT = 'Bars restant';