name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - feature/*
    paths:
      - client/**

jobs:
  client_ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3

      - name: Install dependencies
        run: yarn

      - name: Lint
        run: yarn lint

      - name: Build Next.js app
        run: yarn build