name: CI

on:
  push:
    branches:
      - main
      - feature/*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        working-directory: ./client
        run: yarn
      
      - name: Lint
        working-directory: ./client
        run: yarn lint

      - name: Build Next.js app
        working-directory: ./client
        run: yarn build
