name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - feature/*
    paths:
      - server/**

jobs:
  server_ci:
    runs-on: ubuntu-latest
    steps:
      - name: Set up PHP
        uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: "8.0"

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy .env
        working-directory: ./server
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Install Dependencies
        working-directory: ./server
        run: composer update

      - name: Generate key
        working-directory: ./server
        run: php artisan key:generate

      - name: Directory Permissions
        working-directory: ./server
        run: chmod -R 777 storage bootstrap/cache

      - name: Create Database
        working-directory: ./server
        run: |
          mkdir -p database
          touch database/database.sqlite

      - name: Run Linter
        working-directory: ./server
        run: ./vendor/bin/phpunit
